# Extracted from edirect/setup-deps.pl
requires 'Encode::Locale';
requires 'File::Listing';
requires 'HTML::Parser';
requires 'HTML::Tagset';
requires 'HTML::Tree';
requires 'HTTP::Date';
requires 'HTTP::Message';
requires 'HTTP::Negotiate';
requires 'HTTP::Cookies';
requires 'IO::Socket::SSL';
requires 'LWP';
requires 'LWP::MediaTypes';
requires 'LWP::Protocol::https';
requires 'Mozilla::CA';
requires 'Net::HTTP';
requires 'Time::HiRes';
requires 'URI';
requires 'WWW::RobotRules';
